### ISSUE TITLE
Flutter 3.29 can not build with this plugin since it needs v2 embedding, not v1

### ISSUE THREAD

**Issue by qqqcat** [square/in-app-payments-flutter-plugin#262]
---

From the error logs, it appears that the `square_in_app_payments` plugin's Android code still relies on Flutter's **v1 embedding API** (`PluginRegistry.Registrar`). However, Flutter has removed support for the v1 embedding and now requires all plugins to migrate to the **v2 embedding API**.

This is a known issue, and the latest version of the `square_in_app_payments` plugin (1.7.10) has not yet fully migrated to Flutter's v2 embedding. As a result, using this plugin with newer versions of the Flutter SDK causes build failures.

---

Need fix the problem.

**Comment by Sahad2701** [comment]
🚀 **Resolved: Flutter v1 embedding issue in `square_in_app_payments` plugin**

The build failure related to the usage of `PluginRegistry.Registrar` (deprecated Flutter v1 embedding) has been addressed in this commit:  
🔗 https://github.com/square/in-app-payments-flutter-plugin/pull/263/commits/8d4a9314ac4a1d6586efb9e6f97e3885bd59b781

This patch migrates the plugin to Flutter’s modern **v2 embedding**, making it compatible with the latest Flutter SDKs (e.g., `3.29.2+`).

---

### ⚙️ Temporary Solution

Until this PR is merged and a new version is officially released to `pub.dev`, you can depend on the patched version by adding the following to your `pubspec.yaml`:

```yaml
square_in_app_payments:
  git:
    url: https://github.com/square/in-app-payments-flutter-plugin.git
    ref: 8d4a9314ac4a1d6586efb9e6f97e3885bd59b781
```

Then refresh your dependencies with:

```bash
dart pub cache clean
flutter pub get
```

---

✅ This will unblock you from using `square_in_app_payments` with current Flutter versions without any embedding-related build errors.

Let me know if you need help integrating it!

**Comment by qqqcat** [comment]
That is good advice, I will test that solution.

Thx

**Comment by minkyn** [comment]
Doesn't work.

Building still complains about `error: cannot find symbol` for `io.flutter.plugin.common.PluginRegistry.Registrar`.

**Comment by Sahad2701** [comment]
Fixed:

```
  square_in_app_payments:
    git:
      url: https://github.com/square/in-app-payments-flutter-plugin.git
      ref: 37c0c9c8bf223d47a742a56ed4f5372375ae6e84
```

in this [PR](https://github.com/square/in-app-payments-flutter-plugin/pull/263)
