### ISSUE TITLE
[Apple Pay] NSInvalidArgumentException on payment

### ISSUE THREAD

**Issue by DarthWindu** [square/in-app-payments-flutter-plugin#38]
The exception is thrown when I try to pay with Apple Pay.

- I've uploaded the Apple Pay cert to the Square Development Portal
- The square Cert is the only cert on my merchant id

I'm not quite sure how to approach debugging this.

Here's the exception stack:

```
2019-03-07 14:40:52.802754-0500 Runner[25671:2350011] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]'
*** First throw call stack:
(0x1bec8dea4 0x1bde5da50 0x1bec05384 0x1beb8b870 0x1beb7c3b4 0x103e23cb4 0x103e23f54 0x103e210a8 0x1049cbbfc 0x1049cb9ac 0x103e3b824 0x103e3cdc8 0x103e4aa78 0x1bec1dce4 0x1bec18bac 0x1bec180e0 0x1c0e91584 0x1ebe28c00 0x100f84ed4 0x1be6d6bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

## Flutter Doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Users/pujit/local_bin/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/pujit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/pujit/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • Pujit’s iPhone • 5c2d7444cf703234e996aa07c4c7d758a9d4a0f0 • ios • iOS
      12.1.4
```

## pubspec.yaml

```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cloud_firestore: 0.8.2+1

  firebase_auth: 0.7.0

  # google_sign_in:

  colorize:

  progress_hud:

  square_in_app_payments: 1.0.1

  uuid:

  flutter_slidable:

  flutter_sms: 0.0.3

  dynamic_theme:

  shared_preferences: 0.4.3

  flutter_markdown:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.5.1
  flutter_launcher_icons:
  # screenshots:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
```
