### ISSUE TITLE
duplicate symbol __channel in my plugin

### ISSUE THREAD

**Issue by qq125183592** [square/in-app-payments-flutter-plugin#67]
When I execute 'flutter build ios' , the exception is in the following part: 

```
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Code Signing Warning: Provisioning profile "iOS Team Provisioning Profile: com.letabc.zaxt" for "Runner" contains entitlements that aren't in the entitlements file:
    com.apple.developer.coremedia.hls.low-latency. To use these entitlements, add them to your entitlements file. Otherwise, remove unused entitlements from your provisioning profile.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    duplicate symbol __channel in:
        /Users/yujie/AndroidStudioProjects/zaxt-ios/build/ios/Release-iphoneos/flutter_sound/libflutter_sound.a(FlutterSoundPlugin.o)
        /Users/yujie/AndroidStudioProjects/zaxt-ios/build/ios/Release-iphoneos/square_in_app_payments/libsquare_in_app_payments.a(SquareInAppPaymentsFlutterPlugin.o)
    ld: 1 duplicate symbol for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

my pubspec.yaml:

```
  dio: ^2.0.0 
  flutter_swiper: ^1.1.4 
  audioplayers: ^0.11.0 
  shared_preferences: ^0.5.1+1 
  webview_flutter: ^0.3.6 
  flutter_calendar_carousel: ^1.3.15+6 
  fluttertoast: ^3.0.4 
  event_bus: ^1.1.0 
  cached_network_image: ^0.8.0 
  common_utils: ^1.1.1 
  flutter_sound: ^1.3.7 
  fluro: ^1.5.0 

  flutter_custom_bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git 

  flutter_ijkplayer: ^0.3.2 
  web_socket_channel: ^1.0.12 
  fluwx:
    git: https://github.com/qq125183592/fluwx.git 
  flutter_bugly: ^0.2.3+1 
  package_info: ^0.4.0+3 
  flutter_spinkit: ^3.1.0 
  connectivity: ^0.4.3+1 
  # sona: ^0.0.9+2 
  path_provider: ^0.5.0 
  permission_handler: ^3.0.2 
  flutter_downloader: ^1.1.7 
  image: ^2.1.4 
  sqflite: ^1.1.5 
  flutter_cache_manager: ^0.3.2 
  flutter_easyrefresh: ^1.2.7 
  square_in_app_payments:
    git: https://github.com/square/in-app-payments-flutter-plugin.git
```
